<?php
/**
 * Conflicts / overrule settings screen.
 *
 * @var \HelloGekko\StructuredData\Compat\ConflictManager $manager      Manager.
 * @var array<string,mixed>                               $settings     Current settings.
 * @var array<string,array<string,mixed>>                 $integrations Known integrations.
 * @var array<int,string>                                 $detected     Detected keys.
 *
 * @package HelloGekko\StructuredData
 */

declare( strict_types=1 );

defined( 'ABSPATH' ) || exit;

// phpcs:ignore WordPress.Security.NonceVerification.Recommended
$show_updated = isset( $_GET['updated'] );
?>
<div class="wrap">
	<h1><?php esc_html_e( 'Structured data conflicts', 'hg-structured-data' ); ?></h1>

	<?php if ( $show_updated ) : ?>
		<div class="notice notice-success is-dismissible"><p><?php esc_html_e( 'Settings saved.', 'hg-structured-data' ); ?></p></div>
	<?php endif; ?>

	<p class="description">
		<?php esc_html_e( 'Other SEO/schema plugins may output their own structured data, causing duplicate or conflicting markup. Here you can let this plugin overrule them so it owns the structured data.', 'hg-structured-data' ); ?>
	</p>

	<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>">
		<input type="hidden" name="action" value="hgsd_save_conflicts" />
		<?php wp_nonce_field( 'hgsd_save_conflicts' ); ?>

		<h2><?php esc_html_e( 'Detected plugins', 'hg-structured-data' ); ?></h2>
		<table class="form-table" role="presentation">
			<tbody>
			<?php foreach ( $integrations as $key => $integration ) : ?>
				<?php
				$is_detected = in_array( $key, $detected, true );
				$can_disable = is_callable( $integration['disable'] ?? null );
				?>
				<tr>
					<th scope="row">
						<?php echo esc_html( (string) $integration['label'] ); ?>
						<?php if ( $is_detected ) : ?>
							<span style="color:#16794a;">&nbsp;&#9679; <?php esc_html_e( 'active', 'hg-structured-data' ); ?></span>
						<?php else : ?>
							<span style="color:#8c8f94;">&nbsp;&#9675; <?php esc_html_e( 'not active', 'hg-structured-data' ); ?></span>
						<?php endif; ?>
					</th>
					<td>
						<?php if ( $can_disable ) : ?>
							<label>
								<input type="checkbox" name="hgsd_conflicts[suppress][<?php echo esc_attr( $key ); ?>]" value="1" <?php checked( ! empty( $settings['suppress'][ $key ] ) ); ?> <?php disabled( ! $is_detected ); ?> />
								<?php esc_html_e( 'Disable its structured data (uses the plugin’s own switch — clean)', 'hg-structured-data' ); ?>
							</label>
						<?php else : ?>
							<em class="description">
								<?php esc_html_e( 'No clean off-switch available — use “Strip foreign JSON-LD” below to remove its markup.', 'hg-structured-data' ); ?>
							</em>
						<?php endif; ?>
					</td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>

		<h2><?php esc_html_e( 'Overrule everything', 'hg-structured-data' ); ?></h2>
		<table class="form-table" role="presentation">
			<tr>
				<th scope="row"><?php esc_html_e( 'Strip foreign JSON-LD', 'hg-structured-data' ); ?></th>
				<td>
					<label>
						<input type="checkbox" name="hgsd_conflicts[strip_foreign]" value="1" <?php checked( ! empty( $settings['strip_foreign'] ) ); ?> />
						<?php esc_html_e( 'Remove all JSON-LD output from other plugins, so only this plugin’s structured data remains', 'hg-structured-data' ); ?>
					</label>
					<p class="description">
						<?php esc_html_e( 'This filters the page output and removes every application/ld+json block that is not generated by this plugin. Use it to overrule plugins without a clean off-switch (such as Schema & Structured Data for WP). Test your pages afterwards — it also removes JSON-LD added by your theme or other tools.', 'hg-structured-data' ); ?>
					</p>
				</td>
			</tr>
		</table>

		<?php submit_button( __( 'Save settings', 'hg-structured-data' ) ); ?>
	</form>
</div>
